# Generated by Django 2.2.5 on 2019-11-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stes_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam_questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=400)),
                ('image', models.CharField(default='', max_length=400)),
                ('option1', models.CharField(max_length=400)),
                ('option2', models.CharField(max_length=400)),
                ('option3', models.CharField(max_length=400)),
                ('option4', models.CharField(max_length=400)),
                ('answer', models.CharField(max_length=10)),
            ],
        ),
    ]
